version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/js-columbidae
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: npm run test:cloud
